### ISSUE TITLE
ModuleNotFoundError: No module named 'qiznlp'

### ISSUE THREAD

**Issue by StevenIIV** [Qznan/QizNLP#1]
Traceback (most recent call last):
  File "run_cls.py", line 7, in <module>
    import qiznlp.common.utils as utils
ModuleNotFoundError: No module named 'qiznlp'
(tensorflow) steveniiv@x86_64-apple-darwin13 ~/P/Q/q/run>

**Comment by Qznan** [comment]
注意：如果不是通过pip安装此项目而是直接从github上克隆项目源码，则进行后续操作前需将包显式加入python路径中：

# Linux & Mac
export PYTHONPATH=$PYTHONPATH:<克隆的qiznlp所在dir>
# Windows
set PYTHONPATH=<克隆的qiznlp所在dir>

应该是这个问题，README有提到，设置一下环境路径就好了
